### ISSUE TITLE
Test Requirements

### ISSUE THREAD

**Issue by wbittles** [odpi/egeria-connector-hivemetastore#2]
The following is the proposed test environment for the Hive Metastore connector.
![connectorCohort](https://user-images.githubusercontent.com/47160261/151161601-2f756ceb-3ea5-423a-ac47-f40407b26fd3.svg)

The following issue is to track the progress of implementation and review.

**Comment by wbittles** [comment]
The first step is to build helm charts that deploys the two egeria platforms and adds the connector jar.

**Comment by planetf1** [comment]
See #5 to get a hive metastore setup.

For Egeria one route we have that would probably work:
 * Use the egeria-base helm chart - this deploys kafka & a single egeria platform
 * Switch off the auto-configure & Initially use an external script to configure the two required servers
 * Implement a CI/CD process for this connector that also publishes a docker image (as we do for postgres)
 * Override the configuration of the helm chart to use this custom image
 
 Subsequently the configuration of the servers could be done by either
  a) Modifying the base chart to inject a custom configuration script
  b) Moving to the operator, and providing server configuration documents
  
  For CI/CD of this connector, we might be able to use Kind (see https://github.com/odpi/egeria-database-connectors/blob/main/.github/workflows/connector-test.yml) depending on the ram/storage requirements - in particular of the hive aspect.

**Comment by wbittles** [comment]
I don't have a full enough understanding of where Egeria is now, how we got here or even where we are trying to go , to be able to address these comments as fully as I'd like, and it will be after the connector goes into production that I'lll be able to action this.

In essence this connector is a simple java jar application , so it's difficult to understand why there is an element of risk around building a basic CI pipeline. Have we considered using some of the industry standard tools such as some of the following 
[CI Tools](https://cloud.redhat.com/blog/top-open-source-ci/cd-tools-for-kubernetes-to-know)

These tests will be extremely generic , and can be used by any OMRS connector , all that changes it the entity details on both ends of the connector / cohort. i.e What goes into the system connected to , and what gets returned from an Egeria query on the other side of the cohort. 

@mandy-chessell @cmgrote  I was wondering if this could be an opportunity to centralize some of the testing needed by all OMRS connectors, I'm primarily thinking  of trying to reduce the maintenance concerns around some of our existing connectors. 
Could we develop a CI pipeline that could accept any connector jar, and run a generic set of tests at the getEntity level. 

It would be nice if the base Egeria image didn't contain kafka , if we split the kafka service out it will simplify the charts, especially if we can reuse kafka charts maintained elsewhere.
a chart for egeria platform where the JVM command line can support loader.path options 

Everything else is can be configured via issuing REST commands in whatever binding we choose.

**Comment by planetf1** [comment]
CI/CD

 From that list, we used to use Jenkins in the early days - that has since changed a lot into Jenkins-X which is based on Tekton, and this does form part of the CI/CD pipeline native to Openshift. It's been used to build a connector for another client. Within the core Egeria project we also used Azure DevOps initially, but then moved to GitHub Actions, in part as it has the largest palette of actions, is native to our source code management system, and provides up to 20 7GB 'executors' without charge.
 
 Dev/test workflows should be buildable with any of these tools, so I would suggest that we stick with GitHub actions unless we need capability not available. If we were to look elsewhere, Tekton is the most interesting as it would be good to also ingest metadata from it.
 
 We have an Egeria CTS chart which @cmgrote put together. This already offers the ability to inject a connector jar in for testing. We don't yet have the execution of this automated, but I absolutely see that is relevant to support development of a repository connector. The CTS workbenches are written in custom java
 
 For other testing, we have FVTs -- but these run in a generally simpler environment with a single platform, no kafka, and are scripted through groovy.
 
 We have several aspects to all of these tests
  * Providing the environment for their execution (egeria platforms, kafka etc)
  * Providing the specific connector (this repos output jar)
  * A framework to execute tests
  
  In the postgres repo I provided a simple pipeline which deployed a helm chart with egeria etc & got to the point where we execute tests. It used Kind (kubernetes in docker) -- but the tests themselves were not written. 
 
 So could we have connector testing in a ci/cd pipeline - absolutely
  - initially try with GitHub actions & native agent, plus CTS
  - consider github actions with an external agent, or remote to a k8s cluster if ram limits etc insufficient
   - then can look at better ways of managing the test driver -- there are tools for this.
   
Kafka

The base egeria image contains a kafka connector (including client jars). It does not contain a kafka server. That connector could be split out into a seperate repo, but we'd really need to have a 'good enough' default connector built in. perhaps the in-mem one. 

However I think your point is about the kafka service. For the base/lab charts this is included as a Helm dependency - this means we only spec that dependency, and any overriding values. We do not maintain/include the chart itself. We are ALREADY reusing... Currently we use strimzi for those charts, and bitnami (used previously) for the cts/pts

In the early vdc charts we also had an option to just use an existing kafka deployment, such as IBM Event Streams, and testing was done for this. That's not in the current charts, but easy to add if required. Also the operator itself focusses on core egeria and it's config, not other components - and will use helm to aggregate other components needed for a deployment (demo, prod, test etc)

JVM options

These can already be set. We use the redhat UBI8 openjdk image which provides a set of configuration options, and other environment variables can be set in the PATH. This can be made better (ie to append/prepend rather than replace), but there is no limitation to pointing to a connector jar already

REST commands

This is already how the charts work - the base one, postgres, cts. They all configure via scripts. The operator will augment this and use configs directly.

**Comment by planetf1** [comment]
Links:
 - [Our old devops environment](https://dev.azure.com/ODPi/Egeria/_build)
 - Postgres kind test pipeline - [source](https://github.com/odpi/egeria-database-connectors/blob/main/.github/workflows/connector-test.yml) and [action](https://github.com/odpi/egeria-database-connectors/actions/workflows/verify.yml)
  - [CTS helm chart](https://github.com/odpi/egeria-charts/tree/main/charts/egeria-cts) & [automation issue](https://github.com/odpi/egeria/issues/353)
 - [UBI image](https://access.redhat.com/documentation/en-us/openjdk/11/html/using_openjdk_11_source-to-image_for_openshift/index)
 - Strimzi
  - VDC charts

**Comment by mandy-chessell** [comment]
Is it possible to remove the Spark Driver application and populate HMS via a script?

**Comment by wbittles** [comment]
@mandy-chessell 
The script would have to mimic how spark utilized that metastore, you'd have to basically build an emulator.
Building a spark sample that creates the necessary entities would match what the spark team are requesting.

**Comment by mandy-chessell** [comment]
Support for spark process information is not very interesting to Egeria ecosystem because of the OpenLineage support that captures the processing of spark jobs.  What I hoped we were getting was a catalog of Hive tables that are being created and accessed.

If the spark processor is needed then it suggests that a set of archetypal spark jobs that perform all of the processing patterns of interest are also needed to drive the right patterns of metadata into HMS.

**Comment by wbittles** [comment]
what your getting isn't that much different, 
you will be getting a catalog of the Hive tables that are being created and archived as part of higher level spark processing. service.
